#!/usr/bin/bash

ssh-keygen -t ed25519 -C "icemanexi@github.com"

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
git remote set-url origin git@github.com:icemanexi/BVEXTracker.git
git config --global user.name "thomas"
git config --global user.email "icemanexi@github.com"
